name: Build hugo with musl
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:3.16
    steps:
      - name: Get clang
        run: |
          apk -U upgrade && apk add --no-cache clang-dev musl-dev llvm13-dev git go ca-certificates libc6-compat gcc g++
      - name: Build in Alpine Container
        run: |
          git clone --depth 1 https://github.com/SDLMoe/hugo.git
          cd hugo && sh build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: hugo
          path: hugo/build/hugo
      - uses: actions/download-artifact@v3
        with:
          name: hugo
          path: hugo-bin
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hugo-bin/hugo
          asset_name: hugo
          tag: ${{ github.ref }}
          overwrite: true