name: Build hugo for windows
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get clang
        run: |
          export PATH="/c/msys64/clang64/bin:/c/msys64/usr/bin:$PATH"
          bash -c "pacman -Syu --needed --noconfirm mingw-w64-clang-x86_64-clang mingw-w64-clang-x86_64-go"
          bash -c "pacman -Syu --needed --noconfirm mingw-w64-clang-x86_64-clang mingw-w64-clang-x86_64-go"
        shell: "C:/msys64/usr/bin/bash.exe"
      - name: Build
        run: |
          export PATH="/c/msys64/clang64/bin:/c/msys64/usr/bin:$PATH"
          bash -c "clang -v && bash build.sh"
        shell: "C:/msys64/usr/bin/bash.exe"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/hugo
          asset_name: hugo.exe
          tag: ${{ github.ref }}
          overwrite: true