name: Build hugo for windows
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get clang
        run: |
          export PATH="/c/msys64/clang64/bin:/c/msys64/usr/bin:$PATH"
          pacman -Syu --needed --noconfirm mingw-w64-clang-x86_64-clang mingw-w64-clang-x86_64-go
          pacman -Syu --needed --noconfirm mingw-w64-clang-x86_64-clang mingw-w64-clang-x86_64-go
        shell: bash
      - name: Build
        run: |
          export PATH="/c/msys64/clang64/bin:/c/msys64/usr/bin:$PATH"
          sh build.sh
        shell: bash
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/hugo
          asset_name: hugo.exe
          tag: ${{ github.ref }}
          overwrite: true