name: Build hugo for windows
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare
        run: Remove-Item -Recurse -Force -Path C:\msys64
        shell: powershell
      - name: Get msys2
        uses: msys2/setup-msys2@v2
        with:
          location: C:\msys64
          msystem: CLANG64
      - name: Update msys2
        shell: msys2 {0}
        run: |
          pacman -Syu --needed --noconfirm --overwrite mingw-w64-clang-x86_64-clang mingw-w64-clang-x86_64-go
        continue-on-error: true
      - name: Build
        shell: msys2 {0}
        run: |
          pacman -Syu --needed --noconfirm --overwrite mingw-w64-clang-x86_64-clang mingw-w64-clang-x86_64-go
          export PATH="/clang64/bin:/usr/bin:$PATH" && clang -v && bash build.sh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/hugo
          asset_name: hugo.exe
          tag: ${{ github.ref }}
          overwrite: true