name: Build hugo for macos
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'
      - name: Build
        run: |
          export PATH="$(brew --prefix llvm)/bin:$PATH"
          clang -v && sh build.sh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/hugo
          asset_name: hugo-macos
          tag: ${{ github.ref }}
          overwrite: true