name: Build Statically

on: [workflow_dispatch]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      env:
        CGO_ENABLED: "1"
      run: mkdir -p build && go build --tags extended -o ./build/hugo-${{ matrix.os }} -trimpath -ldflags '-s -w -linkmode "external" -extldflags "-static"' .

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/hugo-${{ matrix.os }}
        asset_name: hugo-${{ matrix.os }}
        tag: ${{ github.ref }}
        overwrite: true