name: Build hugo for macos
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          sh build.sh
        shell: bash
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/hugo
          asset_name: hugo-macos
          tag: ${{ github.ref }}
          overwrite: true