name: Docker
on: workflow_dispatch
jobs:
  container:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Run in container
        run: |
          apk add --update --no-cache gcc g++ musl-dev git ca-certificates libc6-compat libstdc++
          git clone --depth 1 https://github.com/SDLMoe/hugo.git
          cd hugo && sh build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: hugo
          path: hugo/build/hugo
