name: Docker
on: workflow_dispatch
jobs:
  container:
    runs-on: ubuntu-latest
    container: alpine:edge
    steps:
      - name: Run in container
        run: |
          apk add --update --no-cache gcc g++ musl-dev git go ca-certificates libc6-compat libstdc++
          git clone --depth 1 https://github.com/SDLMoe/hugo.git
          cd hugo && sh build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: hugo
          path: hugo/build/hugo
      - uses: actions/download-artifact@v3
        with:
          name: hugo
          path: hugo-bin
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hugo-bin
          asset_name: hugo
          tag: ${{ github.ref }}
          overwrite: true
